# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35e480bcc2f1fed56fb5e9ebaaa95c91637c45ff043e4ee2d59778f111fbd90e1b726d9c7e609734371d183d9f9ee9149c5edddc019eba18b47c817f2bb50dc9

test:
  secret_key_base: 8ab85cb38aab738c48e1355713285a4bfa72ba992507a32b8e9d176e697677b568321c0aba265f9847a4b86a71c1f94cf5e78df9bf748b1f31e3cb5a9e2ea38d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
